export const platformsA = [
  'master-system',
  'super-nintendo',
  'sega-saturn',
  'nintendo-64',
  'xbox',
  'gamecube',
  'xbox-360',
  'playstation-4',
];

export const platformsB = [
  'nintendo',
  'sega-mega-drive',
  'playstation-1',
  'sega-dreamcast',
  'playstation-2',
  'wii',
  'playstation-3',
  'xbox-one',
];

export const platformDetails = [
  {
    name: 'Nintendo (NES)',
    slug: 'nintendo',
    released: 'July 15, 1983',
    developer: 'Nintendo',
    description: 'Reignited a dying industry.',
  },
  {
    name: 'Master System',
    slug: 'master-system',
    released: 'October 20, 1985',
    developer: 'Sega',
    description: 'Let the rivalry begin.',
  },
  {
    name: 'Super NES',
    slug: 'super-nintendo',
    released: 'November 21, 1990',
    developer: 'Nintendo',
    description: 'The 16-bit powerhouse.',
  },
  {
    name: 'Mega Drive',
    slug: 'sega-mega-drive',
    released: 'October 29, 1988',
    developer: 'Sega',
    description: 'The cool kid on the block.',
  },
  {
    name: 'Playstation 1',
    slug: 'playstation-1',
    released: 'December 3, 1994',
    developer: 'Sony',
    description: 'A new contender.',
  },
  {
    name: 'Sega Saturn',
    slug: 'sega-saturn',
    released: 'November 22, 1994',
    developer: 'Sega',
    description: 'A bit of a let down.',
  },
  {
    name: 'Nintendo 64',
    slug: 'nintendo-64',
    released: 'June 23, 1996',
    developer: 'Nintendo',
    description: '32-bit? Nah man let\'s double that',
  },
  {
    name: 'Sega Dreamcast',
    slug: 'sega-dreamcast',
    released: 'November 27, 1998',
    developer: 'Sega',
    description: 'Sega\'s last hurrah',
  },
  {
    name: 'Playstation 2',
    slug: 'playstation-2',
    released: 'March 4, 2000',
    developer: 'Sony',
    description: 'One of the greatest.',
  },
  {
    name: 'Xbox',
    slug: 'xbox',
    released: 'November 15, 2001',
    developer: 'Microsoft',
    description: 'Microsoft throws it\'s cards on the table.',
  },
  {
    name: 'Gamecube',
    slug: 'gamecube',
    released: 'September 14, 2001',
    developer: 'Nintendo',
    description: 'A little bit different.',
  },
  {
    name: 'Xbox 360',
    slug: 'xbox-360',
    released: 'November 22, 2005',
    developer: 'Microsoft',
    description: 'Microsoft proves that they\'re here to stay',
  },
  {
    name: 'Wii',
    slug: 'wii',
    released: 'November 19, 2006',
    developer: 'Nintendo',
    description: 'Nintendo goes in a totally different direction.',
  },
  {
    name: 'Playstation 3',
    slug: 'playstation-3',
    released: 'November 11, 2006',
    developer: 'Sony',
    description: 'Sony continues it\'s dominance.',
  },
  {
    name: 'Wii U',
    slug: 'wii-u',
    released: 'November 18, 2012',
    developer: 'Nintendo',
    description: 'The new Wii, some cool games, but ultimately a failure.',
  },
  {
    name: 'Xbox One',
    slug: 'xbox-one',
    released: 'November 22, 2013',
    developer: 'Microsoft',
    description: 'Another great console.',
  },
  {
    name: 'Playstation 4',
    slug: 'playstation-4',
    released: 'November 15, 2013',
    developer: 'Sony',
    description: 'The latest and greatest, with VR.',
  },
];
